name: elbozor_task
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  json_serializable: ^6.5.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.0

flutter:
  uses-material-design: true